{% set version = "2.1.1" %}

package:
  name: szip
  version: {{ version }}

source:
  url: https://support.hdfgroup.org/ftp/lib-external/szip/{{ version }}/src/szip-{{ version }}.tar.gz
  sha256: 21ee958b4f2d4be2c9cabfa5e1a94877043609ce86fde5f286f105f7ff84d412

build:
  number: 0
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('szip', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - libtool     # [not win]
    - automake    # [not win]
    - autoconf    # [not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libsz.a

about:
  home: http://www.hdfgroup.org/doc_resource/SZIP/
  license: SZIP
  license_family: BSD
  license_file: COPYING
  summary: 'Compression algorithm for HDF and netCDF files'

extra:
  recipe-maintainers:
    - orac_cc
