{% set version = "2.11.0" %}

package:
  name: eccodes
  version: {{ version }}

source:
  url: https://software.ecmwf.int/wiki/download/attachments/131371724/eccodes-{{ version }}-Source.tar.gz
  sha256: 455c05badd3554d6f67dff713f6991164b43ed835e1b8a9da7b728499f22932d

build:
  number: 0
  skip: true  # [win and vc<14]
  detect_binary_files_with_prefix: true
  features:
    - vc14  # [win and py>=35]
  run_exports:
    - {{ pin_subpackage('eccodes', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cmake
    - perl  # [not win]
    - m2-perl  # [win]
    - jasper <=1.900.1 # [not win]
    - libpng  # [not win]
    - libnetcdf
    - libaec  # [not win]
    - hdf5
  run:
    - jasper <=1.900.1 # [not win]
    - libpng  # [not win]
    - libnetcdf
    - libaec  # [not win]
    - hdf5

test:
  commands:
    - codes_info
    - ls $(codes_info -s)  # [not win]
    - ls $(codes_info -d)  # [not win]

about:
  home: https://software.ecmwf.int/wiki/display/ECC/ecCodes+Home
  license: Apache 2.0
  license_family: Apache
  license_file: COPYING
  summary: 'ECMWF ecCodes Copyright 2005-2018 ECMWF.'

extra:
  recipe-maintainers:
    - kmuehlbauer
    - kynan
    - ocefpaf
    - pelson
    - StephanSiemen
    - orac_cc
