{% set version = "3.3.8" %}

package:
  name: fftw
  version: {{ version }}

source:
  url: http://www.fftw.org/fftw-{{ version }}.tar.gz
  sha256: 6113262f6e92c5bd474f2875fa1b01054c4ad5040f6b0da7c03c98821d9ae303

build:
  number: 0
  skip: True # [win]
  run_exports:
    - {{ pin_subpackage('fftw', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - perl   # [not win]
    - libtool     # [not win]
    - automake    # [not win]
    - autoconf    # [not win]
  host:
{% if not compiler('c').startswith("toolchain") %}  # [osx]
    - llvm-openmp >=4.0.1  # [osx]
  run:
    - llvm-openmp >=4.0.1  # [osx]
{% endif %}  # [osx]

test:
  commands:
    - test -f ${PREFIX}/lib/libfftw3f.a          # [not win]
    - test -f ${PREFIX}/lib/libfftw3.a           # [not win]
    - test -f ${PREFIX}/lib/libfftw3l.a          # [not win]
    - test -f ${PREFIX}/lib/libfftw3f_threads.a  # [not win]
    - test -f ${PREFIX}/lib/libfftw3_threads.a   # [not win]
    - test -f ${PREFIX}/lib/libfftw3l_threads.a  # [not win]
    #{% if not 'jc.rl.ac.uk' in environ.get('HOSTNAME', '') %}
    #- test -f ${PREFIX}/lib/libfftw3f_omp.a      # [not win]
    #- test -f ${PREFIX}/lib/libfftw3_omp.a       # [not win]
    #- test -f ${PREFIX}/lib/libfftw3l_omp.a      # [not win]
    #{% endif %}

    # Verify headers are installed
    - test -f ${PREFIX}/include/fftw3.h          # [not win]

    # Verify shared libraries are installed
    {% set fftw_libs = [
            "libfftw3",
            "libfftw3_threads",
            "libfftw3f",
            "libfftw3f_threads",
            "libfftw3l",
            "libfftw3l_threads",
    ] %}
    {% set fftw_omp_libs = [
            "libfftw3_omp",
            "libfftw3f_omp",
            "libfftw3l_omp",
    ] %}

    {% for lib in fftw_libs %}
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/{{ lib }}${SHLIB_EXT}']"  # [unix]
    {% endfor %}

    #{% if not 'jc.rl.ac.uk' in environ.get('HOSTNAME', '') %}
    #{% for lib in fftw_omp_libs %}
    #- python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/{{ lib }}${SHLIB_EXT}']"  # [unix]
    #{% endfor %}
    #{% endif %}

    {% set fftw_libs = ["fftw3f", "fftw3"] %}

about:
  home: http://fftw.org
  license: GPL 2
  license_file: COPYING
  summary: "The fastest Fourier transform in the west."

extra:
  recipe-maintainers:
    - alexbw
    - jakirkham
    - jjhelmus
    - grlee77
    - jschueller
    - beckermr
    - orac_cc